### ISSUE TITLE
Creating cache from iterable adds entries in wrong order

### ISSUE THREAD

**Issue by Tuupertunut** [silentroach/modern-lru#7]
Calling the constructor with an iterable that has entries in some order will cause the entries to be in the opposite order in the cache. The last one to go in will be added as the most recently used entry.

**Comment by silentroach** [comment]
Ha! Thanks a lot, I will fix it

**Comment by silentroach** [comment]
what do you think about 3f8f6db6074cc6a1a5160a09473157300f278992, can you check the test?

**Comment by Tuupertunut** [comment]
Works fine.
